name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Set up Maven cache to speed up builds
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Run Maven to clean, verify, and generate coverage report
      - name: Run Maven Build and Tests
        run: mvn clean verify

      # Set up JaCoCo for coverage reporting
      - name: Generate JaCoCo Coverage Report
        run: mvn jacoco:report

      # Check test coverage (≥ 80%)
      - name: Check Coverage
        run: |
          COVERAGE=$(cat target/site/jacoco/jacoco.xml | grep -A 1 "<counter type=\"INSTRUCTION\"" | grep covered | awk -F'"' '{print $4}' | awk -F'/' '{print ($1/$2)*100}')
          echo "Coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "Coverage ($COVERAGE%) is below 80%. Failing the build."
            exit 1
          fi
        shell: bash

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build Docker image
      - name: Build Docker Image
        run: docker build -t kanban-board:latest .

      # Optional: Log in to Docker Hub and push (uncomment and configure if needed)
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #
      # - name: Push Docker Image
      #   run: docker push kanban-board:latest
